# Generated by Django 5.1 on 2024-09-09 00:04

import datetime
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone', models.CharField(max_length=15)),
                ('first_letter', models.CharField(max_length=1)),
                ('color_id', models.IntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='TodoItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=25)),
                ('description', models.CharField(max_length=200)),
                ('created_at', models.DateField(default=datetime.date.today)),
                ('due_date', models.DateField()),
                ('priority', models.CharField(choices=[('urgent', 'Urgent'), ('medium', 'Medium'), ('low', 'Low')], default='medium', max_length=10)),
                ('status', models.CharField(choices=[('to_do', 'To do'), ('in_progress', 'In progress'), ('await_feedback', 'Await feedback'), ('done', 'Done')], default='to_do', max_length=14)),
                ('assigned_to', models.ManyToManyField(blank=True, related_name='todo_items', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
