# Generated by Django 5.1 on 2024-09-03 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todolist', '0004_alter_contact_first_letter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='first_letter',
            field=models.CharField(max_length=1),
        ),
    ]
